### ISSUE TITLE
Build error at PowerMonitorNode.cpp

### ISSUE THREAD

**Issue by raub** [LabSound/LabSound#109]
https://github.com/LabSound/LabSound/blob/8939f44044cf8e27aa7dd0aa2a40def46da24f7e/src/extended/PowerMonitorNode.cpp#L69

In some cases this produses a build error, specifically at my Travis CI Xenial GCC pass. Although it was quiet with Trusty, it turned up as soon as I switched to Xenial (which updated the GCC version). Just add `std::` or `using std`, just [as you normally do](https://github.com/LabSound/LabSound/search?q=isnan&unscoped_q=isnan).

**Comment by meshula** [comment]
Thanks for the note! Chasing another issue, but I'll get to this asap

**Comment by meshula** [comment]
merged

https://github.com/LabSound/LabSound/pull/117
