### ISSUE TITLE
Samples playback does not work if no input device is available

### ISSUE THREAD

**Issue by Almost-Done** [LabSound/LabSound#110]
It seems that the samples do not play on Windows when no input device is available. If I enable/add an input device (stereo mix, mic etc.), the samples start playing.

Poking around the code it looks like AudioDestinationWin always tries to open the input device in AudioDestinationWin::configure:
`dac.openStream(&outputParams, &inputParams ...`
which fails and closes the stream. Later in AudioDestinationWin::start, dac.startStream fails and render is never called.

If I change AudioDestinationWin to not open or use input in render it fixes the issue, but it feels like a hack. Input should probably be optional on AudioDestination?

**Comment by meshula** [comment]
Thanks for the report.

Weirdly, I think I don't have any machines that don't have an input device of one sort or another.

**Comment by meshula** [comment]
I added a fix here to test: https://github.com/meshula/LabSound/commit/35946222778388aef361c7902c18e4fb167f03c0 similar to the fix proposed by @harmonicvison

**Comment by meshula** [comment]
Merged fix

**Comment by Almost-Done** [comment]
Thank you for the fix! I'll try it out.

**Comment by Almost-Done** [comment]
The fix is not enough in my configuration. I added a couple of comments to the PR.

Summary:
1. There a typo in AudioDestinationWin::configure where the output device ID is used to get input device info.

2. Checking just default input device probed is not enough; probing might succeed but the device is not a capture device and has 0 input channels.

3. On AudioDestinationWin::render, input is still presumed to exist: `m_callback.render(&m_inputBus...`
Maybe make m_inputBus a pointer and only initialize it when AudioDestinationWin::configure configures an input device.

**Comment by meshula** [comment]
Thanks for the feedback!

**Comment by meshula** [comment]
@Almost-Done --- the fix on your branch looks good to me. Would you mind preparing a PR? Otherwise, I'll manually merge the relevant bits.

**Comment by Almost-Done** [comment]
I can do that. I'll take a look at the Linux audio source as well, do you think it needs a similar change?

**Comment by meshula** [comment]
Yes, that error will exist across all variants.

**Comment by meshula** [comment]
Fixed for mac and windows. Linux is still to be done.

**Comment by meshula** [comment]
A couple more fixes for this have been merged, thanks to all who contributed. Please reopen an issue if this problem crops up again.
