### ISSUE TITLE
Race condition in AudioNodeInput causes access violations on Windows

### ISSUE THREAD

**Issue by Almost-Done** [LabSound/LabSound#111]
Unfortunately I don't have a minimum repro for this, but hopefully this analysis will ring a bell:

In AudioNodeInput::pull, when multiple connections, a naked pointer to the internal summing bus is grabbed:
1: `AudioBus* internalSummingBusPtr = internalSummingBus(r);`

AudioNodeInput::pull then calls AudioNodeInput::sumAllConnections, which calls these lines:
2: `AudioBus* connectionBus = output->pull(r, 0, framesToProcess);`
3: `summingBus->sumFrom(*connectionBus);`

The function call at 2 can result in AudioNodeInput::updateInternalBus being called, which resets the internal summing bus, effectively invalidating the naked pointer captured with the call at 1. Then the call at 3 will proceed with an invalid summingBus pointer.

Here's a stack when the summing bus is reset while a naked pointer to it has been captured down the stack:
lab::AudioNodeInput::updateInternalBus   <--this will invalidate naked the pointer
lab::AudioNode::checkNumberOfChannelsForInput
lab::GainNode::checkNumberOfChannelsForInput
lab::AudioNodeOutput::propagateChannelCount
lab::AudioNodeOutput::updateRenderingState
lab::AudioNodeOutput::pull
lab::AudioNodeInput::sumAllConnections   <-- this frame will use the captured pointer about to become invalid
lab::AudioNodeInput::pull <-- this frame captured the naked pointer
lab::AudioNode::pullInputs
lab::AudioNode::processIfNecessary

A quick hacky fix is to change line 3 above to re-grab a pointer to the summing bus after line 2 returns:
`internalSummingBus(r)->sumFrom(*connectionBus);`

**Comment by meshula** [comment]
Thanks for the detailed analysis! Will investigate.

**Comment by meshula** [comment]
I've simplified the logic, and am testing at the moment. Your quick hacky fix is technically a fine workaround in the meantime.

Well I test, I have a question. Is it possible your graph has a loop? I'm trying to reproduce an crash, but haven't come up with a way to accomplish it without introducing a loop.

**Comment by Almost-Done** [comment]
I'll check for loops - it is possible. If you have a possible fix I could try it.

**Comment by meshula** [comment]
My possible fix has an issue with one of the samples, not ready yet...

**Comment by meshula** [comment]
https://github.com/LabSound/LabSound/pull/118

This seems to fix the issue, if you could verify?

**Comment by Almost-Done** [comment]
Verified and fixed! Thank you so much.
