### ISSUE TITLE
Consider replacing CoInitialize with CoInitializeEx

### ISSUE THREAD

**Issue by Almost-Done** [LabSound/LabSound#121]
I think replacing `CoInitialize` with `CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED)` will not have any side-effects. The benefit is the ability to use LabSound in a Windows UWP app container. This change will have to be made in libnyquist as well.

CoInitialize is used in 4 places in RtAudio.cpp, in both LabSound and libnyquist.

**Comment by nporcino-frl** [comment]
I think that makes sense.

**Comment by meshula** [comment]
I think that makes sense; I wonder why RtAudio doesn't do that out of the box? They do flag the condition if detected.

https://github.com/thestk/rtaudio/blob/master/RtAudio.cpp#L2798

**Comment by ddiakopoulos** [comment]
RtAudio shouldn't build as part of the core `libnyquist` libraries, it's just used for playing audio for the example apps. This reduces the surface area of this change to LabSound's RtAudio only.

**Comment by Almost-Done** [comment]
Great. I'll submit a PR then.

**Comment by meshula** [comment]
Hi @Almost-Done, merged CoInitializeEx in https://github.com/LabSound/LabSound/pull/125. Could you verify this does what you need, and re-open if there's an issue?
