### ISSUE TITLE
How to crosscompile for Android

### ISSUE THREAD

**Issue by jrojoCI3** [LabSound/LabSound#135]
Hello, I was trying to use LabSound in Android. I was encouraged when I saw the following in the README.md:

> In the past, LabSound has been demonstrated to work on iOS, Android, and Linux via JACK.

However I'm quite new to crosscompilation and I must admit that I'm a little bit lost in the field. 
As extra information, I'm compiling from a 86x64 Linux (Ubuntu 18.04 distribution). Any advice or hint on how to compile this project for Android would be useful.

Thank you so much.

**Comment by meshula** [comment]
This branch: https://github.com/ltchris/LabSound includes cmake script modifications to enable Android cross compilation. I haven't tested it, but if I were to undertake a port, I'd start by cherry picking from that branch. Unfortunately, that branch has all the files moved around, so it's not a straight forward cherry pick, it would have to be a manual merge.

Before attempting such a thing, I'd suggest building LabSound for your Ubuntu installation, to make sure that much works for you. At this point, I don't have bandwidth to work on it, but I'm happy to answer questions, or accept a PR.

**Comment by jrojoCI3** [comment]
Thank you really much! We will try from there. We could already compile for Linux: that's not an issue and looks like it works fine. If we manage to successfully compile for Android we will try to pull some comments into the documentation and/or some files in case we have to modify them.

**Comment by meshula** [comment]
I've started on a miniaudio backend for LabSound (https://github.com/dr-soft/miniaudio), that should enable Android support, as well as iOS and Raspberry Pi.

**Comment by meshula** [comment]
@jrojoCI3 - the mac_on_rtaudio branch is ready to test for output (not yet for input). The LabSound.cmake file will need a little tweak at the top of the file to set the LABSOUND_USE_MINIAUDIO option to ON, and the LABSOUND_USE_RTAUDIO option to off in the case that the platform is Android. If you have an opportunity to give it a try, feedback would be greatly appreciated.

**Comment by meshula** [comment]
@jrojoCI3 --- the branch, https://github.com/LabSound/LabSound/tree/mac_on_rtaudio now supports input and output, and should automatically configure for Android if you have specified the Android toolchain file when configuring LabSound.

**Comment by jrojoCI3** [comment]
@meshula - First of all, thank you really much for the support! Unfortunately, we're currently on a sprint for another project. However, as soon as we're done with it (probably by the end of January) we will try and test this new branch. Anyway it sounds promising.

**Comment by meshula** [comment]
The device_api_wpi branch has a fully worked miniaudio backend, so it should be a straight shot to the finish line now. As before, you'll need to specify an Android tool chain, and set the LABSOUND_USE_MINIAUDIO variable ON while configuring with Cmake.

**Comment by meshula** [comment]
The miniaudio backend is now merged to master. @jrojoCI3 please re-open this issue if things are not working for you!
