### ISSUE TITLE
SampledAudioNode Start Ofset

### ISSUE THREAD

**Issue by tom-23** [LabSound/LabSound#139]
Hi There,
I'm really enjoying using this library for a project and was wondering if you plan to implement / already have functionality for playing a SampledAudioNode midway through the file. [This article](https://developer.mozilla.org/en-US/docs/Web/API/AudioScheduledSourceNode/start) states that you can add an "offset" to the audio.

**Comment by meshula** [comment]
Hi Tom!

Glad to hear you are enjoying the library :) On the "dev" branch, we are working on addressing a number of issues, such as moving away from the deprecated noteOn, and startGrain functions to the current interfaces.

The master branch has still got the older API though, it's called startGrain. Maybe give this a whirl and see if it does what you need?

```cpp
    void startGrain(double when, double grainOffset);
    void startGrain(double when, double grainOffset, double grainDuration);
```

**Comment by meshula** [comment]
This is working on dev branch
