### ISSUE TITLE
Run example

### ISSUE THREAD

**Issue by HuongNV96** [LabSound/LabSound#141]
Hi all,
After build,I try to run "LabSoundExample" or "libnyquist-examples" example,but they are fail.

LabSoundExample :
Assertion: update:/home/huongnv/LabSound/src/core/AudioContext.cpp:283 - frameLengthInMilliseconds
Assertion: update:/home/huongnv/LabSound/src/core/AudioContext.cpp:284 - graphTickDurationMs
Assertion: update:/home/huongnv/LabSound/src/core/AudioContext.cpp:285 - graphTickDurationUs
NyquistIO::Load(samples/stereo-music-clip.wav) caught internal exception: file not found
unhandled fatal exception: couldn't open samples/stereo-music-clip.wav

libnyquist-examples
[rtaudio] Found: 6 device(s)
	Device: 0 - hw:HDA Intel PCH,0
	Device: 1 - hw:HDA Intel PCH,1
	Device: 2 - hw:HDA Intel PCH,2
	Device: 3 - hw:HDA NVidia,3
	Device: 4 - hw:HDA NVidia,7
	Device: 5 - default

Caught: file not found

Can you help me?

**Comment by meshula** [comment]
Hi there! it says in the output that samples/stereo-music-clip.wav was not found. Be sure to set your working directory to the assets directory, it has the samples directory in it. 

I'm not sure about the libnyquist problem, but I think it is similar, you probably need to set your working directory so that the sample data can be found.

**Comment by meshula** [comment]
We should probably modify the cmake installation to install the sample data, if the sample programs are built to make this set up transparent to users.

**Comment by meshula** [comment]
The new LabSoundDemo project https://github.com/LabSound/LabSoundDemo knows where to find the installed binaries automatically. @HuongNV96 I'm closing this issue. If you are still having trouble, please try the LabSoundDemo and let us know how that goes.
