### ISSUE TITLE
Android build fails to compile with "-lpthread" not found

### ISSUE THREAD

**Issue by robclouth** [LabSound/LabSound#146]
On android you don't need to explicitly link pthread, and so the build fails when you do so.

Commenting out [L43](https://github.com/LabSound/LabSound/blob/c377265a30411f852eaac8bd24b38403c6f20601/cmake/common.cmake#L43) in common.cmake fixed it.

I also commented out including the examples.

**Comment by meshula** [comment]
Ah, that's cool, thanks for the note ~ there must be a standard CMake variable to guard with.

**Comment by meshula** [comment]
@robclouth https://github.com/LabSound/LabSound/commit/676f13fe8f16904029095255069470873a879937 and https://github.com/LabSound/LabSound/commit/12af4daf87155236f3570b8906640af388607a8a should fix it. Out of curiosity, did the default backend work, or did you have to manually select one?

If there's still an issue please reopen this ticket.

**Comment by robclouth** [comment]
That's amazing thanks.
Two more issues:
* Android requires ```OpenSLES``` to be linked in ```target_link_libraries```
* ```elseif (ANDROID)``` needs to be before ```elseif (UNIX)``` in ```LabSound.cmake``` or the conditional exists early and RTAudio is used.

**Comment by meshula** [comment]
@robclouth I'd like to add a github action to automate CI for Android, but I'm an Android n00b. Do we need an Android toolchain file in the LabSound repo, or is Android support built into CMake - if so, could you advise on the command line?

**Comment by meshula** [comment]
Android CI is passing :)
