### ISSUE TITLE
Re-integrate predictive accurate clock, accidentally removed in version 1.0

### ISSUE THREAD

**Issue by xioxin** [LabSound/LabSound#148]
The sample rate I used is 44100.
When the sample rate is 24000, the value obtained by currentTime is correct.

**Comment by meshula** [comment]
Thank you for the report. Could you tell me which platform you are on, and if you are using the default RtAudio backend or another?

**Comment by meshula** [comment]
I see the problem, it's unrelated to platform or backend. The predictive timing code was lost in a code merge, as was the testing code. I'll put it back in...

**Comment by xioxin** [comment]
Thanks.

platform: Androdid
backend: miniaudio

**Comment by meshula** [comment]
I added the functionality back in, with a new name to make the use of the timing api clear. https://github.com/LabSound/LabSound/commit/e5dff50975cac3e5107ebe899f35c6d36660481f

```cpp
    // The current time, measured at the start of the render quantum currently
    // being processed. Most useful in a Node's process routine.
    double currentTime() const;

    // The current epoch (total count of previously processed render quanta)
    // Useful in recurrent graphs to discover if a node has already done its
    // processing for the present quanta.
    uint64_t currentSampleFrame() const;

    // The current time, accurate versus the audio clock. Whereas currentTime
    // advances discretely, once per render quanta, predictedCurrentTime
    // is the sum of currentTime, and the amount of realworld time that has
    // elapsed since the start of the current render quanta. This is useful on
    // the main thread of an application in order to precisely synchronize
    // expected audio events and other systems.
    double predictedCurrentTime() const;


```

There's a little loop that demonstrates the timing data here: https://github.com/LabSound/LabSynthToy/blob/91df549240deb38db5d3846c32babb4f0b5538d9/LabSynthToy.cpp#L186

So far, tested on Windows, it's stable within about a millisecond compared to a std::chrono high_resolution_clock.

**Comment by meshula** [comment]
Okay, the miniaudio backend is reporting correct times now. @xioxin, could you try again with the latest code please?

**Comment by xioxin** [comment]
Work fine. Thanks!

**Comment by meshula** [comment]
Glad to hear it :)
