### ISSUE TITLE
How to get the current playback progress from "SampledAudioNode"?

### ISSUE THREAD

**Issue by xioxin** [LabSound/LabSound#149]
In the old version, I realized this function by reading "m_virtualReadIndex".

**Comment by xioxin** [comment]
I added this method to solve the problem.
This may not be the best way
```
    int32_t SampledAudioNode::getFirstScheduledCursor()
    {
        std::shared_ptr<AudioBus> srcBus = m_sourceBus->valueBus();
        int schedule_count = static_cast<int>(_internals->scheduled.size());
        if (!schedule_count || !srcBus)
            return 0.0;
        Scheduled& s = _internals->scheduled.at(0);
        return s.cursor;
    }
```

**Comment by meshula** [comment]
That will work reliably within a process() call of a node, but there is a thread safety issue if you call it outside of the audio processing thread (the hazard occurs if the schedule is expired, just before _internals->scheduled.at(0);) ~ The chances it will crash are very low, but I think you can do this temporarily... I will think about how to do it in a thread-safe way.

**Comment by meshula** [comment]
@xioxin Almost the same as your suggestion, https://github.com/LabSound/LabSound/commit/fdbf0f40433a4a7d4843c43d0c7d05aee7185b6c

It's threadsafe, by copying the value into a cached location. Please let me know if that's giving the information you need.

```cpp
    // returns the greatest sample index played back by any of the scheduled
    // instances in the most recent render quantum. A value less than zero
    // indicates nothing's playing.
    int32_t getCursor() const;
```

**Comment by xioxin** [comment]
"SampledAudioNode::getCursor" is not working properly.
I changed the code and it now works for me.
![image](https://user-images.githubusercontent.com/5716100/119320142-d5f68880-bcad-11eb-8106-d8e181d32d42.png)

**Comment by meshula** [comment]
Thank you for the report and fix, it has been pushed to https://github.com/LabSound/LabSound/commit/e1d688e01fe1ccb02b101332f2bb8ca0647508b8
