### ISSUE TITLE
SampledAudioNode rewrite doesn't call onEnded callback.

### ISSUE THREAD

**Issue by william-gooch** [LabSound/LabSound#150]
Currently, the `ex_playback_events` example doesn't function because the `onEnded` callback is no longer called from a SampledAudioNode when it finishes.

**Comment by meshula** [comment]
Thanks for the report!

**Comment by meshula** [comment]
@william-gooch Fixed! https://github.com/LabSound/LabSound/commit/15220eaa3a79299a436436c52e65d95f5154bd2f LMK how that goes for you.

**Comment by william-gooch** [comment]
@meshula That's perfect, thank you!
