### ISSUE TITLE
The music will click when it finishes playing

### ISSUE THREAD

**Issue by xioxin** [LabSound/LabSound#155]
https://user-images.githubusercontent.com/5716100/119332732-95057080-bcbb-11eb-834a-9e6a468bf216.mp4

**Comment by meshula** [comment]
I haven't seen this issue ~ what does your code do at the end of playing the clip? Does it suspend context or anything like that?

**Comment by xioxin** [comment]
I went through some attempts.
I found that this problem occurs when the sample rate of the "AudioContext" is different from the audio file.
And I have reproduced the problem on Android, but not on mac.

Maybe it's also related to resampling or miniaudio.

**Comment by meshula** [comment]
That's a good clue, thanks

**Comment by meshula** [comment]
What is the sample rate of the AudioContext, and what is the sample rate of the audio file? Also, how many channels does the audio file have?

**Comment by xioxin** [comment]
Sorry I missed the last message.
AudioContext sample rate: 48000 hz
Audio file sample rate: 44100 hz, 2 channels

**Comment by xioxin** [comment]
I pre-filled the buff with 0, and the problem was solved, I don't know if this is a good solution.

```diff
From c33aa378bc08173e6b2eb4cee9a2457f0f15727c Mon Sep 17 00:00:00 2001
From: xioxin <i@xioxin.com>
Date: Wed, 16 Mar 2022 00:35:43 +0800
Subject: [PATCH] fix

---
 src/core/SampledAudioNode.cpp | 1 +
 1 file changed, 1 insertion(+)

diff --git a/src/core/SampledAudioNode.cpp b/src/core/SampledAudioNode.cpp
index 5e57f598..e0188893 100644
--- a/src/core/SampledAudioNode.cpp
+++ b/src/core/SampledAudioNode.cpp
@@ -376,6 +376,7 @@ namespace lab {
                         src_data->data_in = srcBus->channel(i)->data() + schedule.cursor;
                         src_data->input_frames = remainder;
                         std::array<float, AudioNode::ProcessingSizeInFrames> buff;
+                        std::fill(buff.begin(), buff.end(), 0.0f);
                         src_data->data_out = buff.data();
                         src_data->output_frames = AudioNode::ProcessingSizeInFrames;
                         src_data->src_ratio = 1. / rate;
-- 
2.27.0.windows.1


```

**Comment by meshula** [comment]
A fix is pushed. @xioxin if you have a chance to try the fix, please let me know if it works for you. Please reopen the issue if there is still a click.

**Comment by xioxin** [comment]
Thank you, this fix worked well for me.

**Comment by meshula** [comment]
Great news, thanks for letting me know :)
