### ISSUE TITLE
dynamic switch route is safely?

### ISSUE THREAD

**Issue by imiskolee** [LabSound/LabSound#165]
Hi:

if we have a connection graph is

```
Node A (Scheduled Node)---> Node B ---> Device()
```

if we dynamic insert a new node between A and B, it's working ?

```
disconnect(B,A)
connect(C,A)
connect(B,C)
```

**Comment by meshula** [comment]
It is supposed to work. It is possible that there is a bug for certain node type combinations. What types are your nodes A, B, and C?

**Comment by meshula** [comment]
The LabSoundGraphToy tool can help check issues with node interactions. Have you tried it? https://github.com/LabSound/LabSoundGraphToy Right click on the canvas to create a node, drag connections between terminals.

**Comment by meshula** [comment]
Added a mutex for thread safety. https://github.com/LabSound/LabSound/commit/9daad90c71f6a59c93d0afe7cb198651e9b4c797 Please reopen if the crash happens again!
