### ISSUE TITLE
ConvolverNode node can not safely setImpulse on runtime

### ISSUE THREAD

**Issue by imiskolee** [LabSound/LabSound#166]
program ma crash att

```
#0	0x00000001013d847c in lab::sp_conv_compute(lab::sp_data*, lab::sp_conv*, float*, float*) ()
```

when dynamic update impulse. I think it's data race issue. so can we have a solution for safely update value, locker is ok.

**Comment by meshula** [comment]
Thanks for the report. I will attempt a repro.
