### ISSUE TITLE
[Question] - how to connect hardware input AudioBus to a SampledAudioNode?

### ISSUE THREAD

**Issue by imiskolee** [LabSound/LabSound#168]
Hello:

I know we can use a hardware input node to get samples from the device microphone, but I am not sure it's can be connected to a sampled audio node and keep full data for playback?

or other solution(s)?

**Comment by meshula** [comment]
The microphone can be recorded with the RecorderNode. I only intended it to be used for short samples that will be held in memory, like you might use in a sound-box application or a sampling sequencer. A recording app with unlimited duration would need a different strategy.
