### ISSUE TITLE
AudioParam: Undocumented field m_units

### ISSUE THREAD

**Issue by desttinghim** [LabSound/LabSound#174]
The AudioParam class has a field `m_units` that doesn't correspond to anything in the Web Audio API specification and is not documented anywhere in LabSound. I would guess that it is meant to specify what unit is used for the parameter (hertz, decibels, etc.) but it is only an unsigned integer and I don't see a data structure that maps that integer to a name.

**Comment by meshula** [comment]
I had been meaning to introduce a notion of specifying values in db or linear, but didn't take it over the finish line. It's removed in the ls2 branch, but should be removed here as well.

**Comment by meshula** [comment]
This is removed in the 1.2 release. If you have further questions or comments please feel free to comment here or open a new issue.
