### ISSUE TITLE
Is v1.0.2 ready to release？

### ISSUE THREAD

**Issue by timlyeee** [LabSound/LabSound#175]
It seems like you are working on ls2 for version 2.0.0. However some standards have changed, so I think if there's LabSound v1.0.2 is stable to use.

**Comment by meshula** [comment]
There's one issue that should be fixed for a point release ~ https://github.com/LabSound/LabSound/issues/155

**Comment by meshula** [comment]
A fix has been pushed. I'll tag 1.0.2 after testing.

**Comment by timlyeee** [comment]
Cool! Waiting for ls2 too!

**Comment by meshula** [comment]
Ok, released as v1.1.0, see Release.md for what's changed. Thanks for prompting a release, I appreciate the nudge.
