### ISSUE TITLE
Panner distance gain not working?

### ISSUE THREAD

**Issue by dug9** [LabSound/LabSound#176]
Besides left-to-right, cone and doppler effects, Panner has a distance gain set by the difference between listener and panner positions, and with fade effects controlled by a few parameters, here's a modification to the ex_hrtf_spatialization example:
...
                panner->setDistanceModel(lab::PannerNode::LINEAR_DISTANCE);  
                panner->setRolloffFactor(10.0f);
                panner->setRefDistance(.1f);
                panner->setMaxDistance(20.0f);
... and to elliminate left-right motion effects and focus on distance gain
                panner->setPosition(.1f, x, 0.1f);
x but I don't hear a volume / gain change
x and 
                std::cout << " " << panner->param("distanceGain").get()->value();
x shows all 1 on every slice

goal, to get forward-back motion change of volume like this web audio boom-box example:
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Web_audio_spatialization_basics

Any hypotheses?

more..
I work on freewrl.sf.net which renders www.web3d.org 3D standard scene files, and they updated their standard recently to include web audio equivalent nodes. freewrl is flat C, and with a .cpp module I can interface to and have a bit of the labsound working, but not the distance gain.
Rather than separate threads with Wait(), I visit the labsound nodes on each 3D scene rendering frame, and reset the parameters such as location.

**Comment by meshula** [comment]
Thanks for the report! At this line ~ https://github.com/LabSound/LabSound/blob/00038c56cba092f187f2fdc4781bef917af8e013/src/core/PannerNode.cpp#L274 ~ distanceConeGain is called and should be doing the computation you expect when it gets down to calling the cone effect. I'll have a look at the boom box example.

**Comment by dug9** [comment]
Thanks for the hint. One thing I've found so far today is the DistanceEffect constructor initializes to Inverse(1) which is OK  / normal /expected for OpenAL, and I can verify. Panner seems to initialize to zero so ignors a change to linear(0), but gets a change to exponential(2), or that's what I infer from a few cout/printf, so when getting started if I do this
panner->setDistanceModel(lab::PannerNode::LINEAR_DISTANCE); 
                std::cout << " panner Distance model just after setDistanceModel = " << panner->distanceModel() << std::endl;
I get the correct number for all 3 cases. But DistanceEffect is still on 1 if I set LINEAR_DISTANCE here.

**Comment by dug9** [comment]
In PannerNode.cpp it gets in here when setting to EXPONENTAL or INVERSE but not with LINEAR
m_distanceModel->setValueChanged(
        [this]() {
Hypothesis: PannerNode constructor needs to also initialize this value to 1 so it can detect a change to 0. If so how initialize. Its a fancy field and doesn't take enum, I don't know how to do it.

**Comment by dug9** [comment]
PS if I do a temp fix (initialize DistanceEffect to Linear in its constructor) that doesn't fix the distanceGain problem.

**Comment by dug9** [comment]
BINGO.  rolloffFactor was zero in DistanceEffect and I found it was being mis-initialized in PannerNode.cpp L133
    m_rolloffFactor->setValueChanged(
        [this]() {
            m_distanceEffect->setRolloffFactor(m_rolloffFactor->valueFloat()); //correct, works I get distance gain
            //m_distanceEffect->setRolloffFactor(m_maxDistance->valueFloat()); // WRONG, was  giving me rolloff 0 and no distance gain change, gain stuck on 1

        });

**Comment by meshula** [comment]
Oh wow! Great find, thank you!

**Comment by meshula** [comment]
Hi @dug9 ! Thanks again for the report. I pushed a fix to the bug you reported.

https://github.com/LabSound/LabSound/commit/d8e845a8300b1616000a21e0f2e21704f7b18719
