### ISSUE TITLE
AudioBuffer, AudioBufferSourceNode missing?

### ISSUE THREAD

**Issue by dug9** [LabSound/LabSound#179]
https://frost.cs.uchicago.edu/ref/JavaScript/developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode.html 
- has example in web audio of creating an audiobuffer and audiobuffersourcenode
https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer
https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode 
- chrome and other browsers have it
web3d.org shows a wrapper node specification 
https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-DIS/Part01/components/sound.html#BufferAudioSource 
which I need to implement for freewrl.sf.net and it looks to me like I should be using something like audiobuffer + audiobuffersourcenode to implement web3d BufferAudioSource
Q1. is there another way / set of nodes to implement the same thing in labsound?
Q2. if not, how adopt nodes done in chrome but not yet in LabSound?
- do you have an automated procedure for converting or example or guide / manual procedure?
Thanks

**Comment by meshula** [comment]
There is some discussion here: https://github.com/LabSound/LabSound/issues/172 and https://github.com/LabSound/LabSound/issues/57 and also https://github.com/xioxin/lab_sound_flutter/issues/4, and the noteOn FAQ here https://developer.chrome.com/blog/web-audio-faq/

The basic issue is that ABSN can only play once, and the pattern of a once only node that deletes itself from the graph when finished is extremely complicated. The WebAudio people mention that "implementations are highly optimized for this case," which might be true, but it's really, really complicated to manage in a non-garbage collected system ~ LabSound only uses C++ standard library mechanisms like shared pointers for memory management....

The pattern we usually use in ls to create a buffer

```
    inline std::shared_ptr<AudioBus> MakeBusFromSampleFile(char const*const name, int argc, char** argv)
    {
        std::string path_prefix;
        auto cmds = SplitCommandLine(argc, argv);

        if (cmds.size() > 1) 
            path_prefix = cmds[1] + "/";  // cmds[0] is the path to the exe

        std::string path = path_prefix + name;
        std::shared_ptr<AudioBus> bus = MakeBusFromFile(path, false);

        if (!bus) {
            path = std::string(SAMPLE_SRC_DIR) + "/" + std::string(name);
            bus = MakeBusFromFile(path, false);
        }

        if (!bus) 
            throw std::runtime_error("couldn't open " + path);

        return bus;
    }
```

and then attach it to a _resuable_ node like this:

```
        auto sampledAudio = std::make_shared<SampledAudioNode>(ac);
        {
            ContextRenderLock r(context.get(), "ex_playback_events");
            sampledAudio->setBus(r, musicClip);
        }
        context->connect(context->device(), sampledAudio, 0, 0);
```

A SampledAudioNode is exactly like an AudioBufferSourceNode, except that it does not self-destruct when it finishes playing.

As mentioned in those other threads, LabSound is open to having an ABSN, but so far no one has pushed for it.

**Comment by dug9** [comment]
Thank you very much for the detailed explanation, connecting the dots for me, that SampledAudioNode is like ABSN but re-usable -- I've already been using the SampledAudioNode pattern from Examples, so it should work for me for this web3d node, and re-usable is what I need anyway. I'll close this issue.
