### ISSUE TITLE
ChannelMergerNode - not working for me like web audio api

### ISSUE THREAD

**Issue by dug9** [LabSound/LabSound#181]
https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createChannelSplitter#example 
- shows example of splitter merger with processing in between
x I don't see a channel splitter/merger test in examples.hpp, so made one to duplicate the web audio example
(apologies)
`struct ex_split_merge : public labsound_example
{
    virtual void play(int argc, char ** argv) override final
    {
        std::unique_ptr<lab::AudioContext> context;
        const auto defaultAudioDeviceConfigurations = GetDefaultAudioDeviceConfiguration();
        context = lab::MakeRealtimeAudioContext(defaultAudioDeviceConfigurations.second, defaultAudioDeviceConfigurations.first);
        lab::AudioContext & ac = *context.get();

        std::shared_ptr<ChannelSplitterNode> splitter = std::make_shared<ChannelSplitterNode>(ac,6);
        std::shared_ptr<ChannelMergerNode> merger = std::make_shared<ChannelMergerNode>(ac,6);
        std::shared_ptr<GainNode> gain = std::make_shared<GainNode>(ac);
        auto chan6_source = MakeBusFromSampleFile("samples/6_Channel_ID.wav", argc, argv);
        std::shared_ptr<SampledAudioNode> musicClipNode;
         musicClipNode = std::make_shared<SampledAudioNode>(ac);
        {
            ContextRenderLock r(context.get(), "ex_simple");
            musicClipNode->setBus(r, chan6_source);
        }

        context->connect(splitter, musicClipNode);
        gain->gain()->setValueAtTime(.5f,(float)ac.currentTime());
        context->connect(gain, splitter, 0, 0);
        context->connect(merger, gain, 0, 1);
        context->connect(merger, splitter, 1, 0);
        context->connect(context->device(), merger, 0, 0);
        int i = 0;
        while (i < 16)
        {
            const uint32_t delay_time_ms = 500;

            Wait(std::chrono::milliseconds(delay_time_ms));
            i++;
        };
    }
};`
https://freewrl.sourceforge.io/tests/16_Sound/sound/6_Channel_ID.wav
- sound file I use, a voice iterates over each channel "Left Front Channel" "Right Front Channel"
PROBLEM: I don't hear anything come out.
H0: silly coding mistake
H1: problem with splitter or merger
Q. any thoughts? Thanks.

**Comment by meshula** [comment]
Thanks for the report. This is a great test.

**Comment by dug9** [comment]
thanks and I did find a silly thing - forgot to say musicClip->start(0);
But then the problems started (and more like what I'm seeing in my main application), here I reworked the test a bit
`            ac.connect(splitter, musicClipNode);
            gain->gain()->setValue(1.0f);
            ac.connect(gain, splitter, 0, 1);
            ac.connect(merger, splitter, 1, 0); // A
            ac.connect(merger, gain, 0, 0);     // B
            ac.connect(context->device(), merger, 0, 0);
            musicClipNode->start(0);
`
If I comment out // A or // B I get some output. If I leave them both in, it crashes on the second one, something about an index / array out of bounds.
And of the output I get with just one, it sounds monophonic - equal in both ears. I was expecting it to be left front or right front.

**Comment by meshula** [comment]
for reference, I see that channel merger is supposed to generate a single output with as many channels as inputs, unless a different output channel count is specified in construction.

LabSound doesn't have that constructor variant, but it does have

```
    void setOutputChannelCount(int n) { m_desiredNumberOfOutputChannels = n; }
```

The constructor starts with a single channel output
```
ChannelMergerNode::ChannelMergerNode(AudioContext & ac, int numberOfInputs_)
    : AudioNode(ac, *desc())
    , m_desiredNumberOfOutputChannels(1
```

so that explains the mono output.
Subsequently, I see that the processing loop increments outputChannelIndex and does not test against the actual number outputChannels.

I think I understand the spec to say 
```
let a = number of input channels
let b = number of output channels

if a == b copy 1:1
if a < b copy 1:1 up to a, then zero the other channels
if b < a copy 1:1 up to b, then ignore the other channels
```
if that matches what you think it should do, we can go with that

**Comment by dug9** [comment]
It matches, lets go with it - thanks for taking it on

**Comment by meshula** [comment]
Ok, pushed to top of tree. The merger code is correct, but I only ever hear "front left" from the front left speaker. On a stereo device like I'm testing on, I would have expected to have also heard "front right", so the next question is what happened to the other channels.

**Comment by meshula** [comment]
This is in the 1.2 release. Please reopen the issue if you encounter problems!
