### ISSUE TITLE
Cmake doesn't work in windows for latest main branch commits

### ISSUE THREAD

**Issue by dug9** [LabSound/LabSound#184]
If I roll back to commit "Update README to note miniaudio, and not CoreAudio" then cmake gets the job done.
H: something in commit "Merge device refactor"

**Comment by meshula** [comment]
Thanks for the heads up. Looks like I didn't push the fully merged commit :\
The iOS badge shows failing, but the build succeeded. Hopefully the badge will update shortly.

**Comment by meshula** [comment]
Closing as the build is passing CI.
