### ISSUE TITLE
HRTF loader doesn't return boolean false if .wav not found

### ISSUE THREAD

**Issue by dug9** [LabSound/LabSound#185]
On windows, in the ex_hrtf_spatialization example, if I purposely fail the first load, it returns true anyway, and doesn't get to the second path load:
        if (!ac.loadHrtfDatabase("/fail/hrtf")) {
            std::string path = std::string(SAMPLE_SRC_DIR) + "/hrtf";
            if (!ac.loadHrtfDatabase(path)) { ///DOESNT GET HERE
                printf("Could not load spatialization database");
                return;
            }
        }

I get a console message (and no .wav loading messages):
"""
could not load /fail/hrtf/IRC_Composite_C_R0195_T000_P315.wav
12:00:45 ERROR C:\Users\...\labsound\LabSound\src\internal\src\HRTFPanner.cpp:299: impulse not found /fail/hrtf/IRC_Composite_C_R0195_T000_P315.wav (bad path?)
"""

**Comment by dug9** [comment]
Q. do you prefer Pull Requests or code snippets? 
Snippets:
1. HRTFDatabas.h > struct HRTFDatabaseInfo- add 
    bool files_found_and_loaded = false;
2. HRTFDatabas.h > HRTFDatabase add
public: bool files_found_and_loaded() { return info->files_found_and_loaded; }
3. AudioContext.cpp ::loadHrtfDatabase() change:
    bool loaded = db->database()->files_found_and_loaded();
    loaded = loaded && db->database()->numberOfElevations() > 0 && db->database()->numberOfAzimuths() > 0;
    return loaded;
4. HRTFPanner.cpp in bool HRTFElevation::calculateKernelsForAzimuthElevation() 
change:
    if (!impulseResponse)
    {
        LOG_ERROR("impulse not found %s (bad path?)", resourceName.c_str());
        info->files_found_and_loaded = false;
        return false;
    }
...
    if (!isBusGood)
    {
        info->files_found_and_loaded = false;
         return false;
    }
...
    info->files_found_and_loaded = true;
 
    return true;
}

6. HRTFPanner.cpp > HRTFDatabaseLoader::~HRTFDatabaseLoader() comment out:
    //s_loader = nullptr; //.reset(db) does a pointer swap and the destructor called after new constructor

**Comment by meshula** [comment]
If you can PR, I can merge things after a review, that's my preference. Otherwise, you'll need to wait until I have time to try integrating the change.

**Comment by dug9** [comment]
May I have Labsound/github write access to push a PR branch? Or should I be cloning Labsound on github to put my PRs?

**Comment by meshula** [comment]
The workflow we prefer is that you make a fork, and make the PR from there.

**Comment by dug9** [comment]
Fixed with pull request
