### ISSUE TITLE
No ConstantNode

### ISSUE THREAD

**Issue by Avataren** [LabSound/LabSound#197]
I can't seem to find a ConstantNode among the audio nodes, so I wrote one as I need it to set up a filter envelope. (constant->adsr->filter cutoff param). Is this something that you'd be interested in a PR for, or am I missing a node somewhere that already does this?

**Comment by meshula** [comment]
As far as I know ConstantNode didn't exist when LabSound was first created. I see this https://developer.mozilla.org/en-US/docs/Web/API/ConstantSourceNode ~ it would make sense to me that we'd have such a node, and I can see the utility.

**Comment by meshula** [comment]
Merged, thanks for your implementation.
