### ISSUE TITLE
disconnecting and reconnecting nodes seems to break connection

### ISSUE THREAD

**Issue by Avataren** [LabSound/LabSound#199]
If I first connect two nodes, then disconnect, and finally reconnect, the connection does not seem to function anymore.

context->connect(srcNode, dstNode);
context->disconnect(srcNode, dstNode);
context->connect(srcNode, dstNode);

I sometimes need to disconnect and reconnect nodes for performance reasons, but currently this doesn't work.

**Comment by meshula** [comment]
This is expected to work, the GraphToy relies on it. Thanks for the report.

**Comment by Avataren** [comment]
This is the code that prevents the connection from working:
in AudioNode::processIfNecessary:

`    if (isScheduledNode() && 
        (_self->_scheduler._playbackState < SchedulingState::FADE_IN ||
         _self->_scheduler._playbackState == SchedulingState::FINISHED))
    {
        silenceOutputs(r);
        if (diagnosing_silence)
            ac->diagnosed_silence("Unscheduled");
        return;
    }`

If I comment this out, it works as expected.. _playbackState is "SCHEDULED" at this moment, but it never gets to FADE_IN it seems.

**Comment by Avataren** [comment]
I found that by calling start(0.f) on the node, instead of AudioContext::currentTime, it does seem to work.

**Comment by meshula** [comment]
ah great. The GraphToy expects that connected nodes are not playing on connection otherwise your speakers might explode, especially connecting a weird signal generator.

So I take it you don't need a modification to the code?

**Comment by Avataren** [comment]
I am fine with the way it works, as long as  I know how to get the nodes playing again. All my output is going through an amplitude envelope, so I'm not worried about my speakers. :)

**Comment by meshula** [comment]
Sounds good :)
