### ISSUE TITLE
PingPongDelayNode issue

### ISSUE THREAD

**Issue by Q-Qian** [LabSound/LabSound#213]
`void PingPongDelayNode::BuildSubgraph(AudioContext & ac)
{
    /// @TODO rewrite with individual splitters
    // Input into splitter
    ac.connect(splitter, input, 0, 0);
    
    ac.connect(splitterGain, splitter, 0, 0);
    ac.connect(splitterGain, splitter, 1, 0);
    
    ac.connect(wetGain, splitterGain, 0, 0);
    splitterGain->gain()->setValue(0.5f);
    
    ac.connect(leftDelay, wetGain, 0, 0);
    ac.connect(leftDelay, feedbackGain, 0, 0);
    
    ac.connect(rightDelay, leftDelay, 0, 0);
    ac.connect(feedbackGain, rightDelay, 0, 0);
    
    ac.connect(merger, leftDelay, 0, 0);
    ac.connect(merger, rightDelay, 0, 1);
    
    ac.connect(output, merger, 0, 0);
    
    // Activate with input->output
    ac.connect(output, input, 0, 0);
}`

in the BuildSubgraph function of PingPongDelayNode, seems has some problems: 

1. splitter has two outputs, splitterGain has one input, but, ac.connect(splitterGain, splitter, 1, 0) connect splitter's first output to splitterGain's second input, splitterGain's input index greater than available inputs.
2. why connect splitter with splitterGain twice?
3. merge has two inputs, rightGain has one output, but, ac.connect(merger, rightDelay, 0, 1) connect rightDelay's second output to merger's first input, rightDelay's output index greater than available outputs.

**Comment by meshula** [comment]
I think that the gain was supposed to auto configure to the right number of inputs dynamically.

The implementation should match this

https://github.com/web-audio-components/delay/blob/master/index.js

We should go through that implementation, and the LabSound implementation line by line to make sure they match.

**Comment by Q-Qian** [comment]
> I think that the gain was supposed to auto configure to the right number of inputs dynamically.
> 
> The implementation should match this
> 
> https://github.com/web-audio-components/delay/blob/master/index.js
> 
> We should go through that implementation, and the LabSound implementation line by line to make sure they match.

I think the destIdx and srcIdx were reversed, line 72 ac.connect(splitterGain, splitter, 1, 0) should be ac.connect(splitterGain, splitter, 0, 1); line ac.connect(merger, rightDelay, 0, 1) should be ac.connect(merger, rightDelay, 1, 0);

**Comment by meshula** [comment]
Does it work as you expect with that change? Happy to update the code if so.

**Comment by Q-Qian** [comment]
> Does it work as you expect with that change? Happy to update the code if so.

yes! An error will be reported when running before changing, I will change it and push
