### ISSUE TITLE
Refactor AudioParam inconsistencies

### ISSUE THREAD

**Issue by ddiakopoulos** [LabSound/LabSound#24]
Canonical way of mutating time-varying data on a node is through an AudioParam. Fix cases where the API mucks this up a little bit (cf. PannerNode and several member classes).

**Comment by meshula** [comment]
PannerNode and AudioListener are fixed. Maybe we should do a scrub and create a list here of remaining inconsistencies.

**Comment by meshula** [comment]
Cataloging here.

- [ ] AnalyserNode.h. Parameters, min/max Decibels, smoothing.
- [ ] OscillatorNode.h type
- [ ] PannerNode.h remainder of spatial parameters
- [ ] DiodeNode.h distortion
- [ ] NoiseNode.h type
- [ ] PdNode.h should auto-expose parameters of patch. Also, should be in samples, not extended lib

**Comment by meshula** [comment]
I have a patch in progress for this.

**Comment by meshula** [comment]
https://github.com/LabSound/LabSound/pull/113

**Comment by meshula** [comment]
Merged
