### ISSUE TITLE
Audio hardware query and configuration API

### ISSUE THREAD

**Issue by ddiakopoulos** [LabSound/LabSound#35]
Internally, LabSound's graph engine can handle mixing up to 6 channels (5.1 audio). Presently, no methods are available to configure the AudioDestinationNode's output to anything other than 2-channel 44.1k.

**Comment by meshula** [comment]
I merged @shawwn's work on channel specification on this commit: https://github.com/LabSound/LabSound/commit/0fd6623e6ac8c054099a35691e63e71af62b95b5
