### ISSUE TITLE
Protect AudioScheduledSoureNode::m_startTime and m_endTime

### ISSUE THREAD

**Issue by ddiakopoulos** [LabSound/LabSound#47]
https://chromium.googlesource.com/chromium/blink/+/41ec0c9d0880010388c417e7f521f2e9cd17f3be

**Comment by meshula** [comment]
From the commit: Both AudioScheduledSourceNode::m_startTime and m_endTime can be
accessed by the main thread and the audio thread.  The main thread
sets these when the node is scheduled to start or stop.  The audio
thread needs to read these to determine if the node should actually
start or stop.

A mutex isn't the right for LabSound, but we should put some thought into how to treat these values such that there are not transient impossible states, like a node scheduled to end before it starts.

**Comment by meshula** [comment]
merged
