### ISSUE TITLE
64 bits (double) sample bit depth

### ISSUE THREAD

**Issue by sburkinan** [LabSound/LabSound#53]
Hello,
how difficult it would be to move the whole engine (including effects DSP, analysers with optimisations etc) to 64 bits double ?
I know this is not useful for most usages but I may have a use case (that I cannot disclose) that it would be necessary.

thank you

Steve

**Comment by ddiakopoulos** [comment]
It's not such a huge codebase when you really dig in. I would trivially start just by changing every instance of `float` to `double` and see what happens... might take a few hours. Some 3rd party libraries would be more difficult... I think KissFFT/Ooura only works on floats? And `libynyquist`, our audio loader, will only return float vectors for audio files (not necessarily a problem if you are using an entirely procedural graph).

**Comment by sburkinan** [comment]
Thank you Dimitri, I'll try as soon as I can.

**Comment by meshula** [comment]
One thing you might consider is upgrading the ChannelMerger and ChannelSplitter nodes to allow inputs and outputs of varying bit depth, or perhaps adding a BitDepthAdapter node. That would allow you to specialize only nodes that you need at greater bit depth without having to modify the entire codebase. You'd also have to modify the input and output objects to be bit aware.

**Comment by sburkinan** [comment]
Thank you for your insights
