### ISSUE TITLE
Example program crashes

### ISSUE THREAD

**Issue by MaGetzUb** [LabSound/LabSound#57]
Whenever I run one of the samples, the program always seem to crash in the MakeAudioContext -function, precisely in the AudioListener constructor. 

> Exception thrown at 0x0153AFA7 in LabSoundExamples.exe: 0xC000001D: Illegal Instruction.

What might cause this problem?

![image](https://user-images.githubusercontent.com/1019544/29764325-57bc3bf2-8bdf-11e7-965f-687b9f788ced.png)

I'm using VS2017, but I remember having this same problem with VS2013 as well. Is this some hardware specific, or is there something missing in my configuration settings? I'm trying to run this on Windows 7 (x64) Home premium SP1.

**Comment by meshula** [comment]
Unfortunately I've only got Windows 10 machines; I did a clean pull and build on a fresh machine, and couldn't reproduce.  Did the console log show anything interesting? I get the following:

````
c:\projects\meshula\labsound\src\extended\labsound.cpp @ 48]
        Initialize Context
[c:\projects\meshula\labsound\src\core\defaultaudiodestinationnode.cpp @ 51]
        Hardware Samplerate: 44100.000000
[c:\projects\meshula\labsound\src\internal\src\win\audiodestinationwin.cpp @ 67]
        Using Default Audio Device: Speakers (Realtek High Definition Audio(SST))
[c:\projects\meshula\labsound\src\extended\labsound.cpp @ 26]
        Create UpdateGraphThread
Modulator Frequency: 44
Gain: 203
Modulator Frequency: 38
Gain: 525
Modulator Frequency: 43
Gain: 426
Modulator Frequency: 48
Gain: 721
Modulator Frequency: 48
Gain: 535
Modulator Frequency: 37
````

**Comment by meshula** [comment]
If this issue recurs for you, please reopen an issue.
