### ISSUE TITLE
nodeType() isn't used except one place

### ISSUE THREAD

**Issue by meshula** [LabSound/LabSound#64]
This is the ONLY use of nodeType anywhere, let's just eliminate nodeType. We don't need home made RTTI across the entire API just to support this one check :\

    // First check if this node is an SampledAudioNode. If so, let it know about us so that doppler shift pitch can be taken into account.
    if (node->nodeType() == NodeTypeAudioBufferSource)
    {
        SampledAudioNode * bufferSourceNode = reinterpret_cast<SampledAudioNode*>(node);
        bufferSourceNode->setPannerNode(this);
    }

**Comment by ddiakopoulos** [comment]
Fixed per 8b5116d8c0e75bdd6b1f8723b78fe86944d14ea6
