### ISSUE TITLE
Hangs on Windows process termination

### ISSUE THREAD

**Issue by modulesio** [LabSound/LabSound#69]
For me `RtAudio` hangs on app close on Windows due to the destructor. Basically [this member](https://github.com/LabSound/LabSound/blob/master/src/internal/win/AudioDestinationWin.h#L47).

I don't know if this is a bug in RtAudio or the APIs are being used wrongly but I couldn't figure out how to make it not hang. My fix, which probably isn't right, was to make the member a pointer and not destroy on app termination. This works but it would be nice to have a cleaner shutdown.

**Comment by modulesio** [comment]
Hm, I found this also happens for Linux CLI when I build the the Windows RtAudio platform abstraction on Linux...

**Comment by modulesio** [comment]
Related: https://github.com/LabSound/LabSound/issues/70

**Comment by meshula** [comment]
I briefly looked over the RtAudio code just now for clues, didn't spot an obvious red flag. The behavior you are seeing clearly points to a destruction ordering issue. I'll try to reproduce the hang. When it hangs are you running one of the supplied examples, or your own program?

**Comment by modulesio** [comment]
Thanks for the investigation!

Unfortunately I couldn't repro it anymore :(. In my branch there's been a lot of changes to fix builds on all of the different platforms so I could have broken + later fixed something here.

I'll re-open if I find a repro again.

**Comment by meshula** [comment]
Sounds good. Looking forward to hearing things on new platforms :)
