### ISSUE TITLE
Update thread does not terminate

### ISSUE THREAD

**Issue by modulesio** [LabSound/LabSound#70]
The [AudioContext destructor](https://github.com/LabSound/LabSound/blob/fe5097fdb691942afeb253905fca1e2fc2b1731e/src/core/AudioContext.cpp#L40) sets atomic `updateThreadShouldRun` to `false`.

But that doesn't seem enough to kill [the thread join condition](https://github.com/LabSound/LabSound/blob/fe5097fdb691942afeb253905fca1e2fc2b1731e/src/core/AudioContext.cpp#L201) because it's a disjunction instead of a conjunction, so it's totally possible for this to hang infinitely.

Should the thread condition be `&&`?

**Comment by meshula** [comment]
Thanks for the fix!
https://github.com/LabSound/LabSound/commit/7e5f222ced7a4caa7e00834519d737ec1364f5b8
