### ISSUE TITLE
AnalyserNode lacks setFftSize

### ISSUE THREAD

**Issue by raub** [LabSound/LabSound#75]
Hello.

Walking through the codes, I've just found that `lab::AnalyserNode` class lacks an ability to set `fftSize` value, it has only getter. Also `lab::RealtimeAnalyser` lacks the same thing.

However it exists in **chromium's** implementation of the above classes. And it doesn't seem to be too hacky. I think this method is needed, because [the spec states that this property is settable](https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/fftSize).

As a temporary workaround I could resort to re-creating the `lab::AnalyserNode` instance in my JS (bindings) setter, whenever the `fftSize` value is changed from JS. But it would really be better if we avoided the hackery and put this feature into the core.

**Comment by meshula** [comment]
A little bit of factoring of RealtimeAnalyser could do the trick. m_analysisFrame and m_magnitudeBuffer need to be reinitialized, and it looks like everything will work fine.

**Comment by meshula** [comment]
https://github.com/LabSound/LabSound/pull/113

**Comment by meshula** [comment]
Merged
