### ISSUE TITLE
Implement AudioContext suspend()

### ISSUE THREAD

**Issue by raub** [LabSound/LabSound#78]
Spec states that there is a way to temporarily suspend rendering. However, in LabSound you can only **start** it and never **stop**, APIwise. Actual implementation of the internal `AudioDestination` has the needed `stop()` method, but it is hidden from the exported interfaces. Specifically, `AudioDestinationNode` already has only the `startRendering()` and no `stopRendering()`. Is there a problem with letting people call it?

**Comment by meshula** [comment]
Further note: AudioContext is supposed to emit a statechanged event, and there's supposed to be a status that reports suspended, running, or closed, when the state has changed.

https://webaudio.github.io/web-audio-api/

**Comment by meshula** [comment]
One possible implementation; will stop at buffer resolution. https://github.com/modulesio/LabSound/commit/221e1e28931ddf3752d9e1b4cad15e847d583b00

**Comment by xioxin** [comment]
The pause feature reduces battery consumption when idle.
I am integrating LabSound into Flutter and it is important for mobile to save power.
By the way, how to release the AudioContext, I didn't find the "close" method.

**Comment by meshula** [comment]
Thank you for bumping this issue.

Destructing an AudioContext will release system resources, but does not match the requirements of close. I created a new issue here: https://github.com/LabSound/LabSound/issues/154

For reference, documentation of suspend is here: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/suspend

and the summary is:

```
The suspend() method of the AudioContext Interface suspends the progression of time in the audio context, temporarily halting audio hardware access
```

**Comment by meshula** [comment]
As of  https://github.com/LabSound/LabSound/commit/c720c5e1ee08a5b25ec8a033d2b6deb406fd5ce2 suspend and resume now pause and resume processing. Time stops progressing during suspend, and resumes properly. CPU utilization falls during suspend. Please feel free to reopen if there are any issues.
