### ISSUE TITLE
AVX causes crashes on some CPUs

### ISSUE THREAD

**Issue by raub** [LabSound/LabSound#79]
I've tried running LabSound examples on two different PCs, only to find that it suddenly crashes on my older AMD, whereas newer Intel laptop runs the example fine. The debug build was not helpful at all, because an exception occurs in a very random place.

Then I googled a bit, and found that AVX mode might be the cause. And it turned out to be so. Removing `/arch:AVX` helped.

**Comment by meshula** [comment]
Wow, didn't realize that was an issue. Merged your fix. Probably we should double check the existing vcproj and cmake files as well.

**Comment by raub** [comment]
Yup, do check/edit cmake and vcproj, as I didn't try them at all. The crash was persistent on Win7U AMD Phenom II X6 1075T 3GHz.

**Comment by meshula** [comment]
Fix merged in PR 76

**Comment by meshula** [comment]
Also need this patch for cmake files

**Comment by meshula** [comment]
merged
