### ISSUE TITLE
Need format guessing

### ISSUE THREAD

**Issue by raub** [LabSound/LabSound#82]
Hey! I've got a usecase, and it should probably be resolved on LabSound's side (or libnyquist, who knows). You see, as far as WAA is concerned, it is possible to pass encoded data into it and get it working. However in LabSound you have to pass a file extension, which is somewhat inconvenient and can actually be avoided.

For example:
```

bool compareMagic(const uint8_t *data, const int16_t *magic) {
	
	for (int i = 0; magic[i] != -2; i++) {
		
		if (magic[i] >= 0 && data[i] != magic[i]) {
			return false;
		}
		
	}
	
	return true;
	
}

string getExtension(const uint8_t *data) {
	
	static const int16_t wv[] = { 'w', 'v', 'p', 'k', -2 };
	static const int16_t wav[] = { 0x52, 0x49, 0x46, 0x46, -1, -1, -1, -1, 0x57, 0x41, 0x56, 0x45, -2 };
	static const int16_t flac[] = { 0x66, 0x4C, 0x61, 0x43, -2 };
	static const int16_t pat[] = { 0x47, 0x50, 0x41, 0x54, -2 };
	static const int16_t mid[] = { 0x4D, 0x54, 0x68, 0x64, -2 };
	static const int16_t opus[] = { 'O', 'p', 'u', 's', 'H', 'e', 'a', 'd', -2 };
	static const int16_t ogg[] = { 0x4F, 0x67, 0x67, 0x53, 0x00, 0x02, 0x00, 0x00, -2 };
	
	static const int16_t * numbers[] = { wv, wav, flac, pat, mid, opus, ogg, nullptr };
	static const char* extensions[] = { "wv", "wav", "flac", "pat", "mid", "opus", "ogg" };
	
	for (int i = 0; numbers[i] != nullptr; i++) {
		
		if (compareMagic(data, numbers[i])) {
			return extensions[i];
		}
		
	}
	
	return "";
	
}
```

If you consider this reasonable, let's put it somewhere... Or I can keep it in my bindings.

**Comment by ddiakopoulos** [comment]
This is ideally at the libynyquist layer. As you've already found, I didn't have time to implement many of the in-memory decoders.

**Comment by raub** [comment]
@ddiakopoulos I agree, this is somewhat a "decoding" issue. However, it can be implemented on any layer. For example, LabSound has this function:
`std::unique_ptr<AudioBus> MakeBusFromMemory(const std::vector<uint8_t> & buffer, std::string extension, bool mixToMono)`
It expects a string for extension and passes it then to libnyquist, so either way LabSound should also expose an extensionless `MakeBusFromMemory`.

So, are you going to put into the libnyquist? whereabouts? need any help?

**Comment by ddiakopoulos** [comment]
@raub this will be coming soon in a libnyquist update

**Comment by meshula** [comment]
I suggest we move ahead with this, unless it happened already, and I missed it?

**Comment by ddiakopoulos** [comment]
Nearly 50 weeks after my comment about "coming soon," I actually did this over the weekend and just need to fix one bug/feature with the Ogg format and then I'll push.

**Comment by ddiakopoulos** [comment]
libnyquist was updated and the appropriate function call surfaced in LabSound in 1567ec802d1525569ad3a46c97ef054679714fa7. Enjoy!
