### ISSUE TITLE
Inconsistent return type for AudioContext::listener()

### ISSUE THREAD

**Issue by raub** [LabSound/LabSound#83]
```
AudioListener & listener();
```

Why wouldn't it return a `shared_ptr`? For example, `AudioContext::destination()` does:

```
std::shared_ptr<AudioDestinationNode> destination();
```

**Comment by meshula** [comment]
Internally the listener is stored as a shared pointer. There's no reason not to expose the shared pointer.

**Comment by ddiakopoulos** [comment]
I vaguely remember changing this to return a reference since I thought it should be owned by the `AudioContext` and leased out. I'd prefer the method return `std::weak_ptr` in this case, and `Destination()` should return similarly?

**Comment by raub** [comment]
In my case I need to distribute such a pointer to its respective JS-wrapper, so that the wrapper would call some methods from this pointer.

It was fine with destination because of `shared_ptr`. I knew that I can pass it wherever I want. But now that I had to pass the listener to the wrapper, I was hesitating, since it may be deleted on behalf of the `AudioContext` before I know it, and there's no `shared_ptr` to protect me.

I'm currently [ignoring this issue](https://github.com/raub/node-waa/blob/9f332ab10a7dfb0e8df2f130777c20279476a00e/cpp/base-audio-context.cpp#L143), but there must be a smarter way to do it.

**Comment by meshula** [comment]
1) leave it
2) weak_ptr for listener
3) shared_ptr for listener
4) weak_ptr for listener/destination
5) weak_ptr for all pointers leased out by AudioContext

I'm personally leaning to 3, for consistency, rather than 5, which might be bothersome to work through.

Any thoughts?

**Comment by meshula** [comment]
addressed in: https://github.com/LabSound/LabSound/commit/0bae8e0bbe463c6f69e1fef3c3f038dbdd58e53c

**Comment by meshula** [comment]
merged
