### ISSUE TITLE
Is there a showcase of Apps/Plugins/Experiences built with LabSound?

### ISSUE THREAD

**Issue by nicroto** [LabSound/LabSound#86]
Hey guys,

Kudos for the effort with LabSound. I wanted to extract WebAudio in the past, but never took the time to get it done and was pleasantly surprised to see there is a project that has done it.

I love Web Audio, I think Chris Rogers is a genius! I even had the opportunity to chat with him a couple of times (although it was [quite hard to find him](https://www.quora.com/What-is-Chris-Rogers-WebAudio-API-Apple-CoreAudio-framework-currently-up-to) :) ).

I would like to know if there are any (end-user, not frameworks etc.) projects using LabSound?

Cheers!

**Comment by nicroto** [comment]
@ddiakopoulos It's actually kind of exciting, because that means I am catching you guys early. :)
I am guessing there is nothing public on the VR app, yet?

**Comment by meshula** [comment]
My use case has been rapid prototyping and creative coding, and so far all the uses I know of besides Dimitri's are in that vein. I don't know of anything that's been publicly shared, although some of the test cases and extra nodes (like the Dalek voice changer) came out of that noodling.

**Comment by nicroto** [comment]
That's cool. I will continue following with the project and I hope to get some time to play around with LabSound, soon. Thanks again for starting this, guys. I believe it's inevitable that I'll end up using it on something.

**Comment by ddiakopoulos** [comment]
@nicroto Cheers! 

Nothing on the public on the VR front out yet but it would be cool to eventually have a "showcase" in the readme once some of ongoing NodeJS binding work has finished up.
